apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vue3-boilerplate
  namespace: boilerplate
  labels:
    app:  vue3-boilerplate
spec:
  selector:
    matchLabels:
      app: vue3-boilerplate
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  vue3-boilerplate
    spec:
      containers:
      - name:  vue3-boilerplate
        image:  registry-vpc.cn-chengdu.aliyuncs.com/westapplications/vue3-boilerplate:56c3fef4a8f4aeb5a34d8bf6139e3f47f1329f9b
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
          name:  vue3-boilerplate
      restartPolicy: Always